
[global]
project = "hit_finder_tuning_validation_post_reco_fixed_low_mem"
project_name = "ICARUS BNB $\\nu_\\mu$ + overlay" # toadd
project_label = "Work in progress"
file = "/exp/icarus/app/users/msotgia/analysis/twoDRecoStudies/trackValidations/writerTwoDValidationsHitFinderStudies.root"
outdir = "/exp/icarus/app/users/msotgia/analysis/twoDRecoStudies/hitTuning/plots/validationPlots/lowMem/"
fontsize = 13
labelfontsize = 28
# file_dpi = 50

# --------------------------------------------------------------------
# =====================================================================
# --------------------------------------------------------------------

[analysis_Muons]
merge_on = "Evt"
# filter = [
#     {name = "filter_on", on = "trueEnergy", label = "True energy:GeV", min = 1.0}
# ]
filter = [
    {name = "ratio", product = "energyCompletenessWithVisE", elements = ["energyMatch", "trueVisEnergyCollection"]},
    {name = "ratio", product = "energyCompletenessAllMatchesWithVisE", elements = ["energyAllMatches", "trueVisEnergyCollection"]},
    {name = "ratio", product = "ratioVisECollectionTrueE", elements = ["trueVisEnergyCollection", "trueEnergy"]},
    {name = "ratio", product = "ratioVisEInduction1TrueE", elements = ["trueVisEnergyInduction1", "trueEnergy"]},
    {name = "ratio", product = "ratioVisEInduction2TrueE", elements = ["trueVisEnergyInduction2", "trueEnergy"]},
    {name = "ratio", product = "normalizedEndPointDistanceOnTruth", elements = ["recoTrueDiffEndpoint3d", "trueLength"]},
    {name = "ratio", product = "normalizedEndPointDistanceOnReco", elements = ["recoTrueDiffEndpoint3d", "recoLength"]},
    {name = "filter_on", on = "completeness", label = "Hit completeness", min = 0.4},
    {name = "filter_on", on = "purity", label = "Hit purity", min = 0.4},
]
analysis_supplementaltext = "icaruscode_v10_06_00_06p03:feature/msotgia_add_mvicenzi_reco_stage1\nsbncode:feature/msotgia_hitTuning"

# --------------------------------------------------------------------
# =====================================================================
# --------------------------------------------------------------------

[[analysis_Muons.dataset]]
name = "Muons/D1eNp0pi0_noPulse/1eNp0pi0_noPulse"
label = "$\\mathrm{1e Np 0\\pi^0}$ tune"
style = "style_1eNp0pi0"

[[analysis_Muons.dataset]]
name = "Muons/D1eNpMpi0_noPulse/1eNpMpi0_noPulse"
label = "$\\mathrm{1e Np M\\pi^0}$ tune"
style = "style_1eNpMpi0"

[[analysis_Muons.dataset]]
name = "Muons/D1uNp_noPulse/1uNp_noPulse"
label = "$\\mathrm{1\\mu Np}$ tune"
style = "style_1uNp"

[[analysis_Muons.dataset]]
name = "Muons/DnominalParameters/nominalParameters"
label = "Default hit finder"
style = "style_nominal"

[[analysis_Muons.dataset]]
name = "Muons/DspineParameters/spineParameters"
label = "SPINE hit finder tune (LongMaxHits = 10)"
style = "style_spine"

# --------------------------------------------------------------------
# =====================================================================
# --------------------------------------------------------------------

[[analysis_Muons.plot]]
label = ["Hit completeness", "Hit purity"]
product = ["completeness", "purity"]
yscale = "log"
showmedian = ".1%"
ylabel = "PFPs [#]"
binning = [{bins = 40, limits = [0, 1], flow = "sum"}, {bins = 40, limits = [0, 1], flow = "sum"}]
profile = true
profile_band = false

[[analysis_Muons.plot]]
label = ["$\\Delta_\\mathrm{reco, true}$ track endpoint", "Hit completeness"]
product = ["recoTrueDiffEndpoint3d", "completeness"]
yscale = "log"
ylabel = "PFPs [#]"
binning = [
    {bins = 40, limits = [0, 350], flow = "sum", unit = "cm"},
    {bins = 40, limits = [0, 1], flow = "sum"}
]
profile = true
profile_band = false

# --------------------------------------------------------------------
# =====================================================================
# --------------------------------------------------------------------

# STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES
# S STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYL
# ES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STY
# LES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES ST
# YLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES S
# TYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES 
# STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES STYLES

# --------------------------------------------------------------------
# =====================================================================
# --------------------------------------------------------------------

# Possible choices 
# ['fill', 'step', 'errorbar', 'band', 'bar', 'barstep']

# this overwrites the default style if needed
[style_nominal]
histtype = "step"
yerr = false
color = "k"
linewidth = 1

[style_spine]
histtype = "errorbar"
yerr = true
color = "gray"
# alpha = 0.5
# linestyle = ":"
linewidth = 3

[style_1uNp]
histtype = "step"
color = "tab:orange"
yerr = false
linestyle = "--"
linewidth = 5

[style_1eNpMpi0]
histtype = "step"
color = "tab:blue"
yerr = false
linewidth = 7

[style_1eNp0pi0]
histtype = "step"
color = "tab:green"
yerr = false
linewidth = 9
